### ISSUE TITLE
VOMongoReplicationUrlResolver>>basicLookupReplicaSetStatusIfFound does not use authentication

### ISSUE THREAD

**Issue by maxbareis** [pharo-nosql/voyage#104]
Setup MongoDB ReplicaSet with authentication enabled (SHA1 mechanism)
With this message: (VOMongoRepository
        mongoUrls: {'127.0.0.1:27017' . '127.0.0.1:27018' . '127.0.0.1:27019'}
        database: 'myDB'
        username: 'myUser'
        password: 'myPass') enableReplication
the connectionPool is created.
As soon as you send messages like save on VoyageRoot objects or selectOne on the repository you receive the authentication error.

**Comment by maxbareis** [comment]
Also posted in fogbugz: https://pharo.fogbugz.com/f/cases/22414/VOMongoReplicationUrlResolver-basicLookupReplicaSetStatusIfFound-does-not-use-authentication

**Comment by estebanlm** [comment]
FogBugz is not the place for voyage issues. 
Voyage is not part of Pharo (is just a library you use in Pharo).

**Comment by maxbareis** [comment]
Am Mittwoch, den 19.09.2018, 23:30 -0700 schrieb Esteban Lorenzano:
> FogBugz is not the place for voyage issues.
> Voyage is not part of Pharo (is just a library you use in Pharo).
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

I opened one on github pharo-nosql/voyage. If thats the right place, I
will close the fogbugz issue.

Regards

Max

**Comment by estebanlm** [comment]
I already did it :)
(here is the place, yes)

**Comment by tinchodias** [comment]
Hello @maxbareis 
Could you give more details on how to reproduce this bug?

As I never used authentication in mongodb, I looked at `MongoAuthTest` to learn but don't see how to do `root authMechanism: (SCRAMSHA1AuthMechanism root: root)` in the voyage repo. How do you do it in your case?

I tried:
```
repo := VOMongoRepository
mongoUrls: {'127.0.0.1:27017' . '127.0.0.1:27018' . '127.0.0.1:27019'}
database: 'test'
username: 'pharounittest'
password: 'test'.
repo enableReplication.
repo save: (VOTestDog new name: 'eli'; yourself).
repo selectAll: VOTestDog.
```

Also I did setup a replication environment using the instructions in `MongoReplicationTestResources>>_manual_set_up_`.

Ideally we should create a test case that shows the bug.

**Comment by maxbareis** [comment]
Hi Martin,

I assume this is not implemented yet. I was trying to connect the same
way as you did, expecting this to be handled by voyage (or at least
giving me the opportunity to choose the auth mechanism).

Regards

Max

P.S.: I will try to create a TestCase for all open scenarios.

Am Sonntag, den 23.09.2018, 14:56 -0700 schrieb Martín Dias:

**Comment by noha** [comment]
What is the current status?

**Comment by maxbareis** [comment]
I lost the focus on it, as there was no further need. May be closed from my side, if no one needs the feature.
