### ISSUE TITLE
Update "load voyage" in documentation

### ISSUE THREAD

**Issue by tinchodias** [pharo-nosql/voyage#105]
[the doc](https://ci.inria.fr/pharo-contribution/job/EnterprisePharoBook/lastSuccessfulBuild/artifact/book-result/Voyage/Voyage.html) has this script:

```
Gofer it
url: 'http://smalltalkhub.com/mc/estebanlm/Voyage/main';
configurationOf: 'VoyageMongo';
loadStable.
```

**Comment by undeadparrot** [comment]
The version in catalog seems to be from 2016 :(
