### ISSUE TITLE
Error does not understand makeSeed from VOSeedVersionGenerator>>newVersion

### ISSUE THREAD

**Issue by olekscode** [pharo-nosql/voyage#107]
`VOSeedVersionGenerator` still uses `makeSeed` to generate version (related to #83 and #90).
```Smalltalk
newVersion
    ^UUIDGenerator new makeSeed
```
This causes an error because an instance of `UUIDGenerator` does not understand `makeSeed`. 
And this error happens when I try to save an object, so I can't ignore it
```Smalltalk
anObject save.
```

**Comment by olekscode** [comment]
I fixed it locally by changing
```Smalltalk
newVersion
    ^UUIDGenerator new makeSeed
```
to
```Smalltalk
newVersion
    ^UUIDGenerator new next
```
Should I commit it?

**Comment by estebanlm** [comment]
`VOSeedVersionGenerator` is deprecated (and is there just for backward compatibility). 
It should not be used in new developments. 
Instead, use `VOTimestampVersionGenerator`.

**Comment by olekscode** [comment]
@estebanlm , it wasn't me using `VOSeedVersionGenerator`.

I was following the [TinyBlog tutorial](http://files.pharo.org/books-pdfs/tinyblog-tutorial/2016-02-18-tinyblog-tutorial.pdf) and Voyage raised an error complaining about the missing `makeSeed` (which was removed starting from Pharo 6).

I traced it back to this method of Seaside which uses `newVersion` and `aWorkingCopy` is an instance of `VOSeedVersionGenerator`. https://github.com/SeasideSt/Seaside/blob/master/repository/Seaside-Pharo-Tools-Web.package/WAVersionUploader.class/instance/newVersion..st

Besides, the following two tests of Voyage use `VOSeedVersionGenerator` and fail:
1. https://github.com/pharo-nosql/voyage/blob/master/mc/Voyage-Model-Tests.package/VOSeedVersionGeneratorTest.class/instance/setUp.st
2. https://github.com/pharo-nosql/voyage/blob/master/mc/Voyage-Model-Tests.package/VORepositoryTest.class/instance/testVersionGenerator.st
