### ISSUE TITLE
can't load from Catalog browser

### ISSUE THREAD

**Issue by amiracam** [pharo-nosql/voyage#108]
on latest Pharo i.e. 7.x , I get an install error when loading from the CatalogBrowser

**Comment by undeadparrot** [comment]
Same here. 
I'm running Windows and got this error:
```
Failed to stat file 'C:/Users/smatu/Documents/Pharo/images/Pharo 7.0 - 32bit (development version)/pharo-local/iceberg/magritte-metamodel/magritte/source/ConfigurationOfMagritteContactManager.package/ConfigurationOfMagritteContactManager.class/class/baseConfigurationClassIfAbsent..st': The filename or extension is too long.
```

**Comment by undeadparrot** [comment]
I got it to work by setting PharoLoader to move my images to `C:/pharo`, saving maybe 20 characters,
I'm not sure if this is an OS limitation or something in Pharo.

**Comment by undeadparrot** [comment]
But you're better off installing it via gofer or metacello instead of using catalog browser, that version seems quite old now.

**Comment by RoelofWobben** [comment]
here it does not work when enableiing log path or make it install into the root of my drive.

I used this to install on Windows 10 64 bit with a P7 64 bit image 

Metacello new 
    repository: 'github://pharo-nosql/voyage/mc';
    baseline: 'Voyage';
    load: 'mongo tests'.

and see this  : 

![afbeelding](https://user-images.githubusercontent.com/47429430/53290983-31263180-37ac-11e9-8060-aed7429a8506.png)

**Comment by noha** [comment]
Is this still the case or can this issue be closed?

**Comment by gqw75696** [comment]
There still an issue with the latest Windows version its breaking in the icberg system
the path "C:/Users/me/AppData/Local/PharoLauncher/pharo-local/iceberg/pharo-contributions/Cryptography/source/Cryptography-MSCerts.package/Win32FFICertificateStore.class/instance/cryptUIDlgSelectCertificateFromStore.winHandle.pwszTitle.pwszDisplayString.dwDontUseColumn.flags.reserved..st': The filename or extension is too long." breaks the windows 260 character path limit . currently this path name is 344 chars long of which the filename itself is 110 chars

**Comment by noha** [comment]
Which version of pharo do you use?

**Comment by GideonSwheeler** [comment]
Pharo7.0.3
build: 162, commit: 814fd1b

**Comment by GideonSwheeler** [comment]
I've tried the OSX version and that builds and installs clean

**Comment by noha** [comment]
ok, I'm on it. Iping you when I have it

**Comment by noha** [comment]
If you load voyage from this repo it should be loadable. At least the long filename should have gone @GideonSwheeler

**Comment by noha** [comment]
The catalog entry needs some time. I forgot how to do it and we need a new voyage version first that can be released. But it would be nice if you could tell if it works now

**Comment by GideonSwheeler** [comment]
Installation successful worked a charm thanks  for the speedy response
