### ISSUE TITLE
#theMetaClass called from VODescriptionBuilder>>#collectContainerPragmasFor: has been deprecated.

### ISSUE THREAD

**Issue by SabineMa** [pharo-nosql/voyage#109]
Transcript shows this when loading voyage

#theMetaClass called from VODescriptionBuilder>>#collectContainerPragmasFor: has been deprecated.

https://github.com/pharo-nosql/voyage/blob/master/mc/Voyage-JSON.package/VODescriptionBuilder.class/instance/collectPragmasFor..st

The method ClassDescription>>#theMetaClass called from VODescriptionBuilder>>#collectContainerPragmasFor: has been deprecated.
Please use #classSide instead
The method ClassDescription>>#theMetaClass called from VODescriptionBuilder>>#collectPragmasFor: has been deprecated.
Please use #classSide instead

**Comment by noha** [comment]
Seems to be fixed
