### ISSUE TITLE
Dictionary DNU #leadingChar on saving a MAElementDescription as key in a Dictionary member var (e.g. MAAdaptiveModel as voyage root)

### ISSUE THREAD

**Issue by a2b-alb** [pharo-nosql/voyage#110]
Like discussed on discord -> databases channel with Sabine (2019-04-04):

Initially I tried to save a MAAdaptiveModel subclass as voyage root in mongodb getting a "Instance of Dictionary did not understand #<" error.

Here is the snippet:
```
|ad|
ad := MAAdaptiveModelSubclass new.
ad magritteDescription
    add: MAStringDescription new;
    add: MANumberDescription new.
ad write: 'foo' using: ad magritteDescription children first.
ad write: 123 using: ad magritteDescription children second.
ad save.
```

Then I tried to simplify the snippet letting MAAdaptiveModel out of it:

```
Object subclass: #DbgDictStorage
    instanceVariableNames: 'dict'
    classVariableNames: ''
    package: 'Dbg'

|d|
d := DbgDictStorage new.
d dict: Dictionary new.
d dict at: (MAStringDescription new) put: 'str'.
d save.
```

By this I could track it down to the following error when saving a MAElementDescription in a dictionary as key. Leading to:

Dictionary did not understand #leadingChar

Sabine tracked it down to:
basicSerialize: anObject description: aDescription

I don't know if this is an error or in general one should workaround this with something like:
```
mongoDict
    <mongoDescription>
    ^ VOToOneDescription new
        attributeName: 'dict';
        accessor: (MAPluggableAccessor
            read: [ :model | model getFlatValues ]
            write: [ :model :value | model values: (self valuesFromFlatVOMongo: value) ] );
            yourself
```
Is this an error?

Or is this workaround with MAPluggableAccessor like above necessary and the best way to go ?

Is it not possible to store a MAAdaptiveModel instances as voyage root in mongodb or do I have to treat it some kind special?

System Reporter Info:

Image
Pharo7.0.2
Build information: Pharo-7.0.2+build.152.sha.890f474a81f116ead0e68c8de77790aef4e9a752 (64 Bit)

Virtual Machine
CoInterpreter VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan  5 2019
StackToRegisterMappingCogit VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan  5 2019
VM: 201901051900 https://github.com/OpenSmalltalk/opensmalltalk-vm.git Date: Sat Jan 5 20:00:11 2019 CommitHash: 7a3c6b64 Plugins: 201901051900 https://github.com/OpenSmalltalk/opensmalltalk-vm.git

Unix built on Jan  5 2019 19:12:23 Compiler: 4.8.4
VMMaker versionString VM: 201901051900 https://github.com/OpenSmalltalk/opensmalltalk-vm.git Date: Sat Jan 5 20:00:11 2019 CommitHash: 7a3c6b64 Plugins: 201901051900 https://github.com/OpenSmalltalk/opensmalltalk-vm.git
CoInterpreter VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan  5 2019
StackToRegisterMappingCogit VMMaker.oscog-eem.2504 uuid: a00b0fad-c04c-47a6-8a11-5dbff110ac11 Jan  5 2019

**Comment by noha** [comment]
I'm not sure I understand the problem. Is this still an issue?

**Comment by a2b-alb** [comment]
This is still an issue. I am still using the workaround with MAPluggableAccessor to flatten down the MAAdapiveModel >> values in a production system.
Do you have questions so I can try to make it clearer?

**Comment by noha** [comment]
I've created the subclass as you did and see the Dictionary problem. I'm not sure there is an easy cure. Voyage can now serialize most things but Dictionaries with keys not being as string are difficult.

**Comment by noha** [comment]
I think in that case it is advisable to map the structure intentionally to the lower level

**Comment by a2b-alb** [comment]
This is ok for me and thank you for taking a look at it! 

But I have still one thing in mind looking at the flattening and rebuilding of the Dictionary: I am not sure if I could run into performance issues with a growing dataset while storing or rebuilding a bigger amount of instances. My current implementation looks like:
```
MAAdaptiveModelSubCl class mongoValues
	<mongoDescription>
	^ VOToOneDescription new
		attributeName: 'values';
		accessor: (MAPluggableAccessor
			read: [ :model | model getFlatValues ]
			write: [ :model :aValuesDict |
				model values: (self valuesFromFlatVOMongo: aValuesDict) ] );
		yourself
MAAdaptiveModelSubCl getFlatValues
	|flatValues|
	flatValues := Dictionary new.
	self magritteDescription children doWithIndex: [ :descr :idx |
		MAElementDescriptionStore current addElementDescriptions: descr.
		flatValues at: descr label put: (self readUsing: descr). ].
	^flatValues
MAAdaptiveModelSubCl class valuesFromFlatVOMongo: aValuesDict
	|vals|
	vals := Dictionary new.
	aValuesDict associationsDo: [ :keyAndValue |
		vals
			at: (MAElementDescriptionStore current elementDescriptionFor: keyAndValue key)
			put: keyAndValue value ].
	^vals
```
While MAElementDescriptionStore is a voyage root (singleton) holding possible MAElementDescriptions like a controlled vocabulary:
```
Object subclass: #MAElementDescriptionStore
	instanceVariableNames: 'elementDescriptions'
	classVariableNames: 'Current'
	package: 'A2bCore'
```
Do you see obvious performance killers or do you have a better way?

**Comment by noha** [comment]
I don‘t think I understand it enough but looks not too bad. Performance is always something you need to measure. I‘m closing this for now, ok?
