### ISSUE TITLE
Indirectly referenced objects are not automatically updated

### ISSUE THREAD

**Issue by tinchodias** [pharo-nosql/voyage#13]
Hi. The following code reproduces the issue. First, it saves an Owner which has a Dog, then updates the Owner's name _in a forked image_, then checks the pet's owner name in the _original image_ and shows it's the old name. Finally, the code forces the update of the Owner and checks the name is updated.

Code:

```
"load Voyage+ImageWorker"
Metacello new 
    repository: 'github://estebanlm/voyage/mc';
    baseline: 'VoyageMongo';
    load.
Metacello new 
    smalltalkhubUser: 'PharoExtras' 
    project: 'ImageWorker';
    configuration: 'ImageWorker';
    version: #development;
    load.

"set up db"
repository := VOMongoRepository database: 'indirect-objects'.
repository enableSingleton.

"set up scenario"
repository removeAll: VOTestOwner.
repository removeAll: VOTestDog.
50 milliSeconds asDelay wait.
dog := VOTestDog new name: 'carola'; yourself.
owner := 
    VOTestOwner new 
        name: 'foo'; 
        addPet: dog;
        yourself.
repository save: owner.
dogId := repository idOf: dog.

"clean up"
dog := nil.
3 timesRepeat: [Smalltalk garbageCollect].

"check owner name is foo"
50 milliSeconds asDelay wait.
dog := repository selectOne: VOTestDog where: (Dictionary with: '_id' -> dogId).
('name before: ', dog owner name) logCr.

"clean up"
dog := nil.
3 timesRepeat: [Smalltalk garbageCollect].

"FORKED IMAGE: change owner name to bar"
ImageWorker 
    do: [ 
        (repository selectAll: VOTestOwner) 
            do: [ :each | each name: 'bar'. repository save: each ].
         'change to bar' logCr ]
    within: 3 seconds.

"check owner name is bar"
50 milliSeconds asDelay wait.
dog := repository selectOne: VOTestDog where: (Dictionary with: '_id' -> dogId).
('name after change: ', dog owner name) logCr.

"check owner name after forcing update"
((repository selectAll: VOTestOwner) collect: #name as: Array) logCr.
('name after forced update: ', dog owner name) logCr.
```

 The Transcript prints:

```
'name before: foo'
'name after change: foo'
#('bar')
'name after forced update: bar'
```

**Comment by tinchodias** [comment]
What about this solution?

- add `#syncronize: anObject` to the repository's API (or a better selector).
- create a new sibling of `VOMongoSerializer` and `VOMongoMaterializer` which recursively checks the version of each *root* object referenced (and reload it when outdated).

Some thoughts would be appreciated!

**Comment by tinchodias** [comment]
Well, so I'm working in a prototype of the `#synchronize:` method in [this branch](https://github.com/tinchodias/voyage/tree/indirect-objects)

**Comment by estebanlm** [comment]
well, with the new serializer (who collects all roots), this should be more or less doable :)

**Comment by tinchodias** [comment]
@estebanlm, I don't understand.

Since the serializer is not used to resolve a query, I assume you talked of the materializer. However, I don't see where the roots are collected (VOMongoMaterializer's variables are: 'repository json object'). Maybe you meant to fix this issue by skipping the cache and forcing the materialization when the queried class is marked are "class with automatic sync of indirect objects". But still I don't get it fine.

Anyway, the prototype solution that I proposed some days ago has defects. The main is inefficiency: it just executes a #selectOne:where: for each referenced (persisted) object since that forces the sync.

**Comment by tinchodias** [comment]
I started a [second approach](https://github.com/tinchodias/voyage/tree/indirect_objects2), and works well but tests are making me mad. They pass in graphical mode, but always fail from command-line, so Travis won't like it.

**Comment by tinchodias** [comment]
This week I've been working in a [new branch](https://github.com/tinchodias/voyage/tree/indirect_objects4). This new approach goes in a direction discussed a while ago with @estebanlm. Pseudocode:


On each query (selectOne, selectAll, count, etc.) on a class C
```
- if certain flag is enabled in the class C (or/and in at repository level), then
-- for each instance c of class C (that is result of the query)
--- for each root r referenced from c
---- if r is outdated then synchronize r
```
Where:
- r is outdated when it's in the repository's cache and there is a new version of r in mongodb.
- synchronize r means:
```
- if forceEager (or some flag like that)
-- then update r (just like the query would do for any instance of class C)
-- else do r become forward a new proxy for r
```

The code is currently working but needs refactoring and more testing.

**Comment by tinchodias** [comment]
So, my code is quite finished. It follows the pseudo-code commented above. 

`VOMongoRepository` has these new flags:
- `isEnsuringCurrentReferencesOnQueries`: the enable/disable this feature (disabled by default)
- `isLazySynchronize`: when true, the outdated references are become forward proxies (true by default)

Additionally, any class can define `isEnsuringCurrentReferencesOnQueries` to enable the feature (ignoring repository's flag).

If somebody could review and merge #71, then I'll create a PR with my proposal.

**Comment by tinchodias** [comment]
Close via #80
