### ISSUE TITLE
Method #remove fails to remove object from MongoDB

### ISSUE THREAD

**Issue by dahoward** [pharo-nosql/voyage#133]
The method #remove does not function properly with the MongoDB external repository and has no basic VORepository test method to catch it.  I implemented the fix which consists of a simple change to one method of one class and the addition of an accessor to another class and added a test method as indicated above.  It is on a fork done in our company's name, objectguild.  I will create a pull request on that fork and reference this issue number.

**Comment by noha** [comment]
merged
