### ISSUE TITLE
Arango: 2 tests with DNU

### ISSUE THREAD

**Issue by tinchodias** [pharo-nosql/voyage#149]
Two tests in VOArangoRespotiroyTest error decause a VOArangoUpdateOperation sends #contents to an ArangoDocumentHandle, which doesn't understand. 

Installed Arango and debugged a bit but didn't realize how to fix it.

**Comment by tinchodias** [comment]
@noha any idea?

**Comment by noha** [comment]
I can check, can take a few days. Might be ArangoDB version and voyage are not properly aligned

**Comment by tinchodias** [comment]
I added both tests as `expectedFailures`.

**Comment by noha** [comment]
No Problem, I still need to find time to check. If change ArangoDB client but I though I‘ve adjusted voyage. As Arango is just a preview there is not a problem disabling the tests to keep them green. Just make the ImageWorker tests work

**Comment by noha** [comment]
I will deprecate Arango as it is not nearly finished and degenerates
