### ISSUE TITLE
Update if current

### ISSUE THREAD

**Issue by tinchodias** [pharo-nosql/voyage#15]
It would be nice to signal a conflict error when a save/update of an object that has a newer version (in db).
Additionally, repository's api could support something `#save:onConflict:`.

**Comment by tinchodias** [comment]
Working in this issue in https://github.com/tinchodias/voyage/tree/saveconflict

Still missing:
- configuration in repository's api
- more testing

**Comment by tinchodias** [comment]
Ready to merge!

**Comment by tinchodias** [comment]
Waiting for reviews and merge in #62

**Comment by noha** [comment]
This is merged.
