### ISSUE TITLE
in VOSeedVersionGenerator >> #newVersion method throws DNU

### ISSUE THREAD

**Issue by CafeKrem** [pharo-nosql/voyage#154]
```smalltalk
newVersion
	^ UUIDGenerator new makeSeed
```
UIIDGenerator DoesNotUnderstand 
on Pharo 7 and Pharo 8

**Comment by noha** [comment]
Yes, that's why there is on the class side `isDefault
	"In versions >= 5, we prefer VOMongoishVersionGenerator"
	^ SystemVersion current major < 5`

**Comment by tinchodias** [comment]
To clean up we could consider that from now there are no users of Voyage in Pharo 4 or less and do something about this code... remove the class?

**Comment by noha** [comment]
Right! We decided to support down to pharo6. So this is deprecated. Can you provide a PR?

**Comment by CafeKrem** [comment]
yes  , I will do it
