### ISSUE TITLE
VOMongoRepository InstanceVariable host & port are unuse

### ISSUE THREAD

**Issue by CafeKrem** [pharo-nosql/voyage#156]
I think we should remove those 2 IVs and add methods to get those data from the IV *mongoUrls*.

What do you think ?

**Comment by noha** [comment]
I think you are right. They were used in the past but I guess when @tinchodias added the replica support he changed it to use mongo urls and so the instVars not needed anymore. Can you provide a pull request?

**Comment by noha** [comment]
And if the commit message contains "Fixes #156" it will close this issue when merged

**Comment by CafeKrem** [comment]
Yes I will do.
