### ISSUE TITLE
[Voyage-mongo-tests] VOMongoTest class >> #isAbstract strange implementation

### ISSUE THREAD

**Issue by CafeKrem** [pharo-nosql/voyage#158]
I found something strange in **VOMongoTest**

```smalltalk
isAbstract
	^ super isAbstract or: [ self name = #VOMongoTest ]
```

why we check if his superclass is abstract ?  We only need to check if to test if *self* is abstract and only him.

**Comment by noha** [comment]
Looks strange to me, too. Can you provide a PR?

**Comment by CafeKrem** [comment]
yes
