### ISSUE TITLE
why using UUID instead of VOSeedVersionGenerator

### ISSUE THREAD

**Issue by CafeKrem** [pharo-nosql/voyage#161]
in order to generate an Object ID in **VOArangoRepository** 
```smalltalk 
newId
	^ UUID new asString
``` 

instead of using VOSeedVersionGenerator ? 

```smalltalk 
newId
	^ VOSeedVersionGenerator next
```

**Comment by noha** [comment]
Why not? Would please ask those questions on discord and do not open issues on everything?

**Comment by noha** [comment]
These tickets have the potential to linger around and we have to house keep. Chat is good for asking questions. Pull requests are create to propose something. Do not expect just you create a ticket somebody will do something
