### ISSUE TITLE
Mongo connections not being returned to pool

### ISSUE THREAD

**Issue by jvalteren** [pharo-nosql/voyage#164]
The change to integrate the SDAM client introduced an issue with the connection pool (MongoPool), causing lots of new connections to be created, which are almost never returned to the pool. Perhaps these connections aren't closed properly either, but I am not certain about this. (I have made several changes in [our fork](https://github.com/objectguild/voyage) and haven't tested the behavior of the upstream original).

**Problem**
In #mongoDo: the MongoPool object allocates a connection using #next, after which it [evaluates aBlockClosure](https://github.com/pharo-nosql/mongotalk/blob/1a718ff2f487230286f0ce0dc730662b141cfad4/mc/Mongo-Client.package/MongoPool.class/instance/mongoDo..st#L12). After that, it should return the connection to the pool.

However, in [the latest update of the Mongo implementation of basicSelectOne](https://github.com/pharo-nosql/voyage/commit/625800096b4a53d266cdaa5a504beefc0f96ab59#diff-c7e8d7ba22c99b929e90a29a0bf77833), the block closure changed significantly. Now it uses a non-local return, which cuts the MongoPool short and prevents returning of the connection to the pool. Potentially, this has other side effects as well, since all code after evaluating aBlockClosure in MongoPool>>mongoDo: is ignored.

**(Potential) Solution**
This can be solved by changing the block implementation to revert back to a simple `detect: where` statement. I will create a pull request with the change.

**Comment by noha** [comment]
This is fixed in mongotalk 1.25
