### ISSUE TITLE
MongoClient instances are not GCd

### ISSUE THREAD

**Issue by SabineMa** [pharo-nosql/voyage#183]
Problem is that the processes in the process browser do not disappear, also after waiting for some time. 
Also, they remain after GC.

**I have to manually stop the MongoClient instances to get them GCd. This is not the expected behavior.**

If there are too many processes, the image crashes.

<img width="842" alt="Bildschirmfoto 2023-09-02 um 15 54 55" src="https://github.com/pharo-nosql/voyage/assets/13763544/0921a358-05e8-4236-b683-fb55b6390a9c">

### **How to reproduce** 

"get new pharo 11-64bit stable image from launcher and load this code"

```
Metacello new
    repository: 'github://pharo-nosql/voyage/mc';

(or  repository: 'github://pharo-nosql/voyage:mongo-driver-v5/mc'; - error occurs on both drivers)

    baseline: 'Voyage';
    onWarningLog;
    load: 'mongo tests'.

Metacello new baseline: 'Voyage'; lock.

Metacello new
    baseline: 'Grease';
    githubUser: 'SeasideSt' project: 'Grease' commitish: 'master' path: 'repository';
 onConflictUseIncoming;
    load.
```

"create demo class - note that you have this in your mongo db or try with your DB content. This is a very basic class just for demo, incomplete if you really want to fetch the objects"
	
```
newModelClass := Object classInstaller make: [ :aClassBuilder |
		aClassBuilder
			name: 'RKAPerson';
			package: 'RKA24-Model' ].

	newModelClass class compile: 'isVoyageRoot 
	^ true'.

	newModelClass class compile: 'mongoContainer 	
		^ VOContainer new
		  collectionName: ''Persons'';
		  kind: RKAPerson;
		  enableMissingContent;
		  yourself'.
```

"create mongo instance and auth"

```
mongo := Mongo host: 'localhost' port: 27017.
mongo open.

mongo authMechanism: (SCRAMSHA1AuthMechanism root: mongo).
mongo
	authenticateUsername: 'xxx'
	password: 'xxx'
	database: (mongo databaseNamed: 'admin').
mongo
	authenticateUsername: 'xxx'
	password: 'xxx'
	database: (mongo databaseNamed: 'xxx').
```
		
"fetch the person 30 times from the database but do nothing with them"	

```
30 timesRepeat:   [
	 (VOMongoRepository 
				host: 'localhost'
				database: 'K1000308'
				username:  'xxx'
				password:  'xxx'  ) 	
					selectMany: RKAPerson
				   where: {('emailLowercase' -> 'emailxxx@gmail.com')} asDictionary] .
```
			
"ok, now we have all the processes in the process browser"			
`(Process allInstances select: [ :each | each name beginsWith: 'Monitor' ]) inspect.`

"want them to disappear - force gc"
`10 timesRepeat: [ Smalltalk garbageCollect  ].`

"no. they remain and do not disappear. If I make this too often, the image crashes"

**"I found out that I have to send stop to the mongo clients"**

`MongoClient allInstances do: [:each | each stop].`

"again gc"
 
`10 timesRepeat: [ Smalltalk garbageCollect  ].`
"now they are gone"

`(Process allInstances select: [ :each | each name beginsWith: 'Monitor' ]) inspect.`

"Summary is that I have to call stop to the mongo clients. This is not the expected behavior "

**Comment by estebanlm** [comment]
trying a fix on: https://github.com/pharo-nosql/voyage/commit/f84e6e5d713823c694639fe5cc98d06d3afca8f7

**Comment by SabineMa** [comment]
I confirm that, with this fix the Process instances disappear. Thank you, @estebanlm
