### ISSUE TITLE
objects and reversedObjects are out of sync after GC (randomly)

### ISSUE THREAD

**Issue by SabineMa** [pharo-nosql/voyage#187]
**Brief description:**
There is a short moment which occurs randomly when the `objects` and `reversedObjects` dictionaries are not in sync (= do not contain the same objects). If, exactly in that moment, one of that object is saved in mongo, its data is duplicated.

Perhaps also one important point is, that if the cache is out of sync and one object is retrieved again from the database, it is **not** added newly to the reversedObjects. Then you have to rebuild the cache (remove all sessions, logoff all users in our case) which is only a bad workaround.

**Long description:**
- Having some objects which are fetched from mongo and in the cache - normal case
- in the cache they this objects are in the `objects` and `reversedObjects` dictionaries as it should be.
`objects` is a `WeakValueDictionary`
`reversedObjects` is a `WeakKeyDictionary`

This screen shows that normal case:
<img width="813" alt="Bildschirmfoto 2024-10-17 um 18 48 44" src="https://github.com/user-attachments/assets/a5fb52a5-1ea3-497f-b49f-ec7aea2ab73c">

- Important for the bug description: this objects are not referenced by any other object in the system and for this reason are allowed to be Gcd (at some "random" moment for this reason this bug is difficult to reproduce).
- The Bug is: there is a moment in which the cache is out of sync. 
- This means the objects in the  `objects` attribute and the `reversedObjects` attribute are not the same.

**This has a very bad side effect:** 
If in this moment, when the cache is out of sync, one of this objects should be saved, voyage does not find the OID in the `reversedObjects` attribute and this leads to duplicating the data of this object in the database. **It duplicates the object in Mongo which is very bad**

**Now more information and reproduction:**
It took me a long time to reproduce this and we had several chats in discord about this, @estebanlm . 
In the following I show how to reproduce this. But this is with my model and our configuration in my image and please tell me If you need more information or if you can not reproduce it with this in your image, @estebanlm  

As we have one mongo database per customer, we do also have one `VOCache` per customer.
The caches are administrated by `RKARepositoryManager` which holds one Repository per customer.
`RKAMongoRepository`  is a subclass of `VOMongoRepository`. it only defines another poolSize (2) and retrieving possibilities.

<img width="545" alt="Bildschirmfoto 2024-10-17 um 19 11 00" src="https://github.com/user-attachments/assets/863e688c-afe7-457a-a601-a098b582af79">

In the following code snippet for reproducing the bug, I am doing the following:

1. Resetting the repository manager to be clean.
2. Then reading some objects from mongo.
3. Hold them in a collection (they are referenced and so they are not GCd)
4. read the cache
5. wait a little bit
6. do GC
7. and now the cache is out of sync
8. Sometimes it gets out of sync also without actively calling the gc. I think then the gc was just running by its own. Sometimes also the delay is not needed...randomly...

```
| theCollection |
RKARepositoryManager customerRepositories: WeakValueDictionary new.
theCollection := (RKASingleReceipt selectAllSingleReceiptsOfCompany: 'K1002432')  .
(RKARepositoryManager customerRepositories at: 'K1002432') cache.
(Delay forSeconds: 2) wait.
theCollection := nil.
Smalltalk garbageCollect .
(RKARepositoryManager customerRepositories at: 'K1002432') cache inspect.
```
<img width="813" alt="Bildschirmfoto 2024-10-17 um 19 06 52" src="https://github.com/user-attachments/assets/3b536f96-5f13-428b-aeff-fb0cb97a9aba">

https://github.com/user-attachments/assets/c28bb64e-488e-4419-8f3e-706a6a902333

The objects which are missing in the reversed objects after gc are exactly that objects which are no longer referenced by any other object and then are gcd.

As far as our discussions in the past, we were saying that this should never occur (having not the same objects in objects/reversedObjects). In my case this leads to a duplication of the data because mongo then does not find the object in the reversed objects/does not find the oid/and is thinkin that the object is new. But it is not new.
 
btw. I think this was also in the old driver but interestingly did not occur that often. I am not sure if this is true because we do have this objects RKASingleReceipt new. Explanation: I have to go back a bit: until spring, we had a model that had a close link between the company, people and travel and receipts. The company was also always in the session. Therefore, the objects were always referenced from the moment they were read from the database. However, after taking your advice to heart @Norbert Hartl  - very good advice, Norbert - that the design is not good for larger amounts of data, which is the case with us now, we have chosen a different design for the new expense report/individual receipts feature. The person no longer knows their single receipts. Only the single receipts  know their persons but not the persons their receipts. This means that there are no longer many references to the individual receipts, which is why this problem occurs for me in the new area. But we already had it in the old versions. I have built extra workouts for this. Something like when the repo is out of sync logoff all users and build a new cache!
So, i say my impression is that the bug occurs more often in the new driver but possible the bug more often occurs in the new model perhaps 

 
Here to be complete the methods used above:

```
selectAllSingleReceiptsOfCompany: aCustomerNumber

	^ (self repositoryNamed: aCustomerNumber)
		  selectMany: RKASingleReceipt
		  where: self queryDictNotNilPerson
		  order: self sortOrderAscendingDict
		  limit: 10000
		  offset: 0
```

```
repositoryNamed: aString
	^ self customerRepositories
		  at: aString
		  ifAbsentPut: [
		  RKAMongoRepository repositoryForCustomerNumber: aString ]
```

This is my current setting and VM but I would say there was never a version where I did not have this problem
(Pharo 6-Pharo 11)

Pharo 11

Virtual Machine
---------------
/Users/sabinem/Documents/Pharo/vms/110-x64/Pharo.app/Contents/MacOS/Pharo
CoInterpreter VMMaker-tonel.1 uuid: 872d53e1-b3c1-0d00-86f3-f7200df24b96 Sep 14 2023
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 872d53e1-b3c1-0d00-86f3-f7200df24b96 Sep 14 2023
v10.0.7 - Commit: b66dd582 - Date: 2023-09-13 15:14:31 +0200

Pharo 10.0.7 built on Sep 14 2023 16:05:00 Compiler: Apple LLVM 12.0.5 (clang-1205.0.22.9)
VMMaker versionString v10.0.7 - Commit: b66dd582 - Date: 2023-09-13 15:14:31 +0200
CoInterpreter VMMaker-tonel.1 uuid: 872d53e1-b3c1-0d00-86f3-f7200df24b96 Sep 14 2023
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 872d53e1-b3c1-0d00-86f3-f7200df24b96 Sep 14 2023

/Users/sabinem/Documents/Pharo/images/Pharo 11.0 - 64bit (oktober4)/Pharo 11.0 - 64bit (oktober4).image
Pharo11.0.0
Build information: Pharo-11.0.0+build.726.sha.aece1b5473acf3830a0e082c1bc3a15d4ff3522b (64 Bit)
Unnamed

**Comment by SabineMa** [comment]
this is copied from discord because I think that the point that after having the cache mismatch one time, the fact that re fetching the object from the database is not adding it again to the cache put be a workaround fix if we can not find the real reason for the issue

https://discord.com/channels/223421264751099906/300255715337961474/1296758258454757406


Norbert Hartl — heute um 10:54 Uhr
@Sabine Manaa I wonder what is the effect if the collections are not in sync. The difference between both collections should all be objects that are not referenced anywhere, right? So to me the question is: what is the reason an object you want to store is not in the collection? As you want to save it there is obviously a strong reference to that object and hence should not be one that is missing. 
How many objects are in the VOCache? We need to exclude the compaction of the cache.
So I just started to think about this. But instead making the difference between the two collections responsible for the cause I would think about the GC maintaing the weak collection messes up with the hashing
So when you check the collections you need to check if the object is not in the collection or if it cannot be found.
Sabine Manaa — heute um 11:14 Uhr
@Norbert Hartl interesting points. Thank you for thinking about it.

The "history" of the issue is, that I had and am having doubled data. 
But  it rarely happens. 
I was searching for the reason.
Then I put a halt in development in for exactly that point, when the "double saving" would start. 
Then I recognized that in this case, there ist always an unbalanced state in that two collections.
This seemed to be related. 
Then I was asking esteban and he confirmed. 
The both collections have to include the same objects.
You are right by saying that for saving there must be a strong relation to this object!

**But we have to consider that, after having the "cache-mismatch", when that object which is only in the objects but not in the reversed objects, is re-fetched, then it is not added to the reversed objects.** @Esteban Lorenzano perhaps this would be a workaround fix...

**Comment by SabineMa** [comment]
After having an interesting discussion with @noha at discord, I am able do provide the code to demonstrate the doubling of objets in mongo:

Before, I see in MongoDB Compass this - having ONE receipt:

![Bildschirmfoto 2024-10-18 um 12 13 48](https://github.com/user-attachments/assets/c84b9217-dcec-453a-82fb-fe578b17915d)

```
| theCollection theDoubleCandidate theRepositoryForSaving theCustomerNumber |
theCustomerNumber := 'K1002467'.
RKARepositoryManager customerRepositories: WeakValueDictionary new.
theCollection := (RKASingleReceipt selectAllSingleReceiptsOfCompany: theCustomerNumber)  .
(RKARepositoryManager customerRepositories at: theCustomerNumber) cache.
(Delay forSeconds: 2) wait.
theCollection := nil.
Smalltalk garbageCollect .
(RKARepositoryManager customerRepositories at: theCustomerNumber) cache inspect.
theDoubleCandidate := (RKASingleReceipt selectAllSingleReceiptsOfCompany: theCustomerNumber)  first .
 theRepositoryForSaving := RKARepositoryManager repositoryNamed: theCustomerNumber.
theRepositoryForSaving save: theDoubleCandidate
```

after that code above which should re read the existing object in mongo, it is doubled:

![Bildschirmfoto 2024-10-18 um 12 17 54](https://github.com/user-attachments/assets/359eaac9-a60c-4351-97a7-bba4da88efae)

**Comment by SabineMa** [comment]
Here comes the code to reproduce the issue from a clan Pharo 11 image.

1. Start Image Pharo 11 -64bit from launcher.

2. Load Voyage

```
Metacello new 
	repository: 'github://pharo-nosql/voyage/mc';
	baseline: 'Voyage';
	load: 'mongo tests'.
```

3. change the printOn: of VOCache

```
VOCache compile: '
printOn: aStream
	aStream 
		nextPutAll: ''Cache'';
		nextPut: $(;
		nextPutAll: objects size asString;
		space;
		nextPutAll: ''objects;'';
		nextPutAll: reversedObjects size asString;
		space;
		nextPutAll: ''reversedObjects'';
		nextPut: $).'
```

4.) create the test data - then we have 1000 TestPilot objects in the database

```
| theRepository |
theRepository := ( VOMongoRepository 
		host:  VOMongoRepository defaultHost 
		database: 'aaa').		
1 to: 1000 do: [:index | 
		theRepository save:  (VOTestPilot new name: 'Esteban', index asString ) ] .
```
![Bildschirmfoto 2024-10-18 um 19 22 19](https://github.com/user-attachments/assets/2f209d15-36fd-49d0-bc41-fba335892cae)

5.) Do some select and between Garbage Collection. Write the cache size in the Transcript while doing this.
		
```
| theRepository  thePilots thePilot theLaterDuplicated | 
Transcript clear.
theRepository :=  ( VOMongoRepository host:  VOMongoRepository defaultHost database: 'aaa') .
Transcript crShow: 'step 1', theRepository cache printString.		
thePilots :=  theRepository   selectAll: VOTestPilot .
Transcript crShow: 'step 2',theRepository cache printString.		
thePilot := thePilots first.
thePilots := nil.
Smalltalk garbageCollect .
Transcript crShow: 'step 3',theRepository cache printString.		
theLaterDuplicated := (theRepository selectAll: VOTestPilot ) last.
theRepository save: theLaterDuplicated .
Transcript crShow: 'step 4',theRepository cache printString.		
```

6.) the result is that we have 1001 objects in the database:		
![Bildschirmfoto 2024-10-18 um 19 24 51](https://github.com/user-attachments/assets/057b30bf-44cc-4c0f-8bbd-5bbfe568268b)

Transcript shows this:


> step 1Cache(0 objects;0 reversedObjects)
> step 2Cache(1000 objects;1000 reversedObjects)
> step 3Cache(1000 objects;1 reversedObjects)
> step 4Cache(1001 objects;2 reversedObjects)		

This is the doubled object:
![Bildschirmfoto 2024-10-18 um 19 26 49](https://github.com/user-attachments/assets/8a33897e-e99d-4f26-986d-94bf2214c2f8)

7.) Now drop the database, do everything again but without this line:
`Smalltalk garbageCollect .`
And everything is fine and we remain with 1000 objects in the database

**Comment by yannij** [comment]
In step 5, change
`theLaterDuplicated := (theRepository selectAll: VOTestPilot ) last.`
to
`theLaterDuplicated := (theRepository selectAll: VOTestPilot ) detect: [:each | each name = thePilot name].`

That would make theLaterDuplicated object strongly held, and not subject to garbage collection.

Also, notice that the reversedObjects size is 1. I would expect that one object to be thePilot object.

**Comment by SabineMa** [comment]
It is

> In step 5, change `theLaterDuplicated := (theRepository selectAll: VOTestPilot ) last.` to `theLaterDuplicated := (theRepository selectAll: VOTestPilot ) detect: [:each | each name = thePilot name].`
> 
> That would make theLaterDuplicated object strongly held, and not subject to garbage collection.
> 
> Also, notice that the reversedObjects size is 1. I would expect that one object to be thePilot object.
 
@yannij your suggestion fixes probably the demo case. But in our application, we can not change everything to this. This is just a small example to show the out-of-sync case. We rely on the mechanism to work properly and it does not.

**Comment by yannij** [comment]
I suspect your problem could be related to your model change. IIUC, you previously held all receipts in a collection instance variable of the Person. Now you have done away with the collection, and instead have a "foreign key" in the receipt, to be able to find Person. If the Person is strongly held in your app, then the receipts would be strongly held only when they were in the collection held by the Person. With the model change, the receipts are no longer strongly held.

What is unclear is how the receipt object is being held in your app.

**Comment by SabineMa** [comment]
@yannij you exactly summarise the situation except that it is not a change of the model but a new part of the model, where I use this new paradigm. 

The receipts are queried on demand. Some are held in the session (e.g. the last edited receipt). But they are - in difference to the other model classes (company <->person<->trip) not all hold as reliable as them. 

We are planning in the long run to move forward to have more of this "loose" connections because we move to having a REST API where the receipts are just queried and written and no state and no session is holding anything.

I understand the reason for your question "What is unclear is how the receipt object is being held in your app." because this seems to be the reason for the bug. 

**But saying that each object has to be strongly referenced for that everything is fine, can not be the solution**. This would mean building something like a second cache. I want to rely on the VOCache and that it is working properly.

**Comment by yannij** [comment]
I agree that VOCache has a problem. The objects collection is used to answer selectAll:, and reversedObjects is used to answer #isNew. So, it depends on these collections being in sync, but you have a case where they are out-of-sync after a garbageCollect call. Whether or not the database objects are strongly held, the collections should always be in-sync.

My idea for a fix would be to make reversedObjects non-weak, and arrange for a specialized WeakValueAssociation to be used by the objects collection. The specialized weak association would remove the corresponding model value from the reversedObjects.

**Comment by SabineMa** [comment]
@yannij  thanks for your thoughts and your time! you have completely thought into the problem and understood it. I had already suspected something like this but never thought it through. @estebanlm, what is your opinion on this? it would be great to have a solution here, because the bug has already cost me sleep. besides, we can then continue with our plans here with the application (rest-api)

**Comment by estebanlm** [comment]
Ok, I made a PR that hopefully will fix the issue, thank you all for your insights.  I implemented as suggested a way to make sure that the dictionary is in sync when a key in `reversedObjects` is mourned.

**Comment by SabineMa** [comment]
Hi @estebanlm, thank you. I am testing it by using it for first in my development environment while working. I will come back to you in a few weeks with feedback. 🦊

**Comment by estebanlm** [comment]
weeks!?!? I don't want to hold this PR as long :P
Joking, thanks and I wait for it ;)

**Comment by SabineMa** [comment]
ah - we had a misunderstanding.
As I understand it, you are still working on a solution for Pharo 12. For me it is good, if you integrate the commit in master! I looked at the changes and did some experiments and everything was fine. In production we are on the old driver.

**Comment by estebanlm** [comment]
no, this solution works in P11 to P13... I am dropping support for P10 and below since the solution uses new ephemeron functionality.
