### ISSUE TITLE
Concurrency issue with cached MongoCollections

### ISSUE THREAD

**Issue by zecke** [pharo-nosql/voyage#25]
`  VOMongoRepositoryResolver>>#collectionAt: aClass inDatabase: db
    | collectionName |
    collectionName := self collectionNameFor: aClass.
     ^(collections
        at: collectionName
        ifAbsentPut: [ db addCollection: collectionName ])
        setDatabase: db name: collectionName;
        yourself.
`

The returned code is a MongoCollection that will be used concurrently. This means process A will start with database A but if process B uses the same collection and changes it to database B.. process A might make a query against database B (and not A).

This will start failing if both processes make a query at the same time and then one process will "steal" the response from another process. I have worked-around it by adding a "copy" before setting the database. It would be better to have the MongoCollection be cached per process.

**Comment by tinchodias** [comment]
DynamicVariable sounds like a good option to implement the MongoCollection cache per process.

I guess in this kind of issues is hard to create a test, no? or do you figure out a way to force it?

**Comment by zecke** [comment]
> On 22 Apr 2016, at 06:05, Martín Dias <notifications@github.com> wrote:
> 
> DynamicVariable sounds like a good option to implement the MongoCollection cache per process.
> 
> I guess in this kind of issues is hard to create a test, no? or do you figure out a way to force it?

Depending on what part we want to test it is "easy". One could so something like this.


```
| blockThread1 blockThread2 mongo1 mongo2 |
blockThread1 := Semaphore new.
blockThread2 := Semaphore new.
complThread2 := Semaphore new.
workDone := Semaphore new.


thread1 := [
	| db |
	db := 23.
	mongo1 := ... collectionAt: testClass in: db.
	workDone signal.
	blockThread1 wait.
	self assert: mongo1 db equals: 23.
] newProcess.
thread1 name: 'Test using same MongoCollection in two threads. Thread#1'.
thread1 resume.
workDone wait.

thread2 := [
	| db |
	...
	db := 42.
	mongo2 := ... collectionAt: testClass in: db.
	workDone signal.
	blockThread2 wait.
	self assert: mongo2 db equals: 42.
	complThread2 signal. "put around with [] ensure? to not block in case of failure"
] newProcess.
workDone wait.

"We have forced the first process to execute and block first, then started the
second one."

"Make sure both operate on different instances of a MongoCollection
self deny: mongo1 == mongo2.

"Resume the second process first"
blockThread2 signal.
complThread2 wait.
blockThread1 signal
complThread1 wait.
```


Obviously it has blanks but should illustrate the race condition that happens by using the same MongoCollection in different thread. Yes a DynamicVariavle/ProcessVariable seems to be a good workaround. The other option is to change the MongoTalk API so MongoCollection does not carry a db instance variable but gets the DB in all calls.

**Comment by zecke** [comment]
I would prefer if we could avoid using MongoCollection instance at all.

1. MongoDB seems to create the collection on the fly anyway
2. We don't pass specific MongoCollection parameters/indices anyway

**Comment by tinchodias** [comment]
+1

About the cache:

I supposed the main goal of caching MongoCollection instances in the resolver is to avoid calling 'create collection' command (MongoDatabase>>addCollection:) before each insert/update/query operation. That's why, I first assumed it was mandatory to ensure the collection exists before performing one of such operations. BUT! an experiment shows that query and insert have the same result if the collection doesn't exist and then the 'create collection' wouldn't be needed at all. So the cache looks unneeded.

Experiment:

```
	| pool results collectionName |
	pool := VOMongoSessionPool 
		host: 'localhost' 
		port: 27031
		database: 'test'
		username: ''
		password: ''.

	collectionName := 'col_', (UUID new asString36 first: 5).

	pool withDatabase: [ :db | 

		'Query all rows in an (inexistant) collection' logCr.
		results := LinkedList new.
		db query: (
			MongoQuery new
				collection: (MongoCollection database: db name: collectionName);
				doBlock: [:each | results add: each ];
				yourself).
		results size logCr.
		(db command: {'getLastError'->1} asDictionary) logCr.


		'Insert one row in the (yet inexistant) collection' logCr.
		db insert: {{ 'now' -> 'true' } asDictionary} collection: collectionName.
		(db command: {'getLastError'->1} asDictionary) logCr.


		'Query rows in the (now existant) collection' logCr.
		results := LinkedList new.
		db query: (
			MongoQuery new
				collection: (MongoCollection database: db name: collectionName);
				doBlock: [:each | results add: each ];
				yourself).				
		results size logCr.
		(db command: {'getLastError'->1} asDictionary) logCr.
	].
```

Logs:

```
'Query all rows in an (inexistant) collection'
0
a Dictionary('connectionId'->63 'err'->nil 'n'->0 'ok'->1.0 'syncMillis'->0 'writtenTo'->nil )

'Insert one row in the (yet inexistant) collection'
a Dictionary('connectionId'->63 'err'->nil 'n'->0 'ok'->1.0 'syncMillis'->0 'writtenTo'->nil )

'Query rows in the (now existant) collection'
1
a Dictionary('connectionId'->63 'err'->nil 'n'->0 'ok'->1.0 'syncMillis'->0 'writtenTo'->nil )
```

**Comment by noha** [comment]
I don't understand the problem. The collection are kept in a repository resolver which is attached to a repository. The repository has the database. How can it be that this is ever called with a different database?

**Comment by zecke** [comment]
> On 15 Jun 2016, at 09:47, Norbert Hartl <notifications@github.com> wrote:
> 
> I don't understand the problem. The collection are kept in a repository resolver which is attached to a repository. The repository has the database. How can it be that this is ever called with a different database?

You have one repository resolver (which has one MongoCollection) per "application" but for each process calling >>#withDatabase: you get a unique instance of the MongoDatabase. And many processes call (self collectionAt: aClass inDatabase: db). But there is also only _one_ MongoCollection instance per collection but:

```
collectionAt: aClass inDatabase: db
 	| collectionName |
	collectionName := self collectionNameFor: aClass.
	 ^(collections 
		at: collectionName
		ifAbsentPut: [ db addCollection: collectionName ])
		setDatabase: db name: collectionName;
		yourself
```

is setting the _last_ database. Process A/Process B might still use the same MongoCollection with two different databases. So depending on scheduling you might end up both requests being sent on the _same_ database. During stress tests this is what happened.


holger
