### ISSUE TITLE
VOMongoCache compaction occurs too late

### ISSUE THREAD

**Issue by zecke** [pharo-nosql/voyage#26]
I have 100k+ objects and access them randomly. This leads to a VOMongoCache of 1000+ entries that are mostly dead (the OID points to nil). The issue is that compaction will occur way too late because the lower limit is too high.

The size of the VOMongoCache adds a measurable latency to the handling of the system. I don't have a workaround but the compactLimit seems to be too high.

**Comment by tinchodias** [comment]
Maybe Voyage could have some automated benchmarks. I've experience with Smark (http://smalltalkhub.com/mc/StefanMarr/SMark/main). Well... the benchmarks could be executed from command line with some external framework, but I've no experience on that.

I mean, some "automated" benchmarks to execute them on our computers "manually". Additionally, in Fuel tried "automated" regular benchmarking using SMark, with executions in an exclusive Jenkins slave. Sadly, not sure how useful the measurements are since finally we never payed too much attention to them :). But the plots are nice: https://ci.inria.fr/pharo-contribution/job/Fuel-Benchmarks/plot/.

**Comment by tinchodias** [comment]
I wanted to learn more of VOMongoCache's behavior and did some tests and benchmarks. 

I found the large number of dead entries (the OID points to nil and viceversa, in other collection). In addition, I watched how the compactLimit changes after performCompact. In most executions it changed from the initial 8000 to 6400. In other executions it went to 2000 or close. What @zecke suggest is to modify minimumCompactLimit (currently 2000), right?

However, despite I confirm the "dead cache entries", I didn't see latency in basic operations. In the benchmarks, insert, update and selectOne are constant (few milliseconds). Where is the latency?

Script:

	| log repository |
	repository := VOMongoTestResource current tearDown; setUp; repository.
	log := LinkedList new.

	1 to: 10000 do: [ :index |
		| pilot |
		pilot := VOTestPilot new
			name: 'B', index asString;
			yourself.
		repository save: pilot.

		(index \\ 10) isZero ifTrue: [ 
			log add: {
				[ pilot name: 'C', index asString. repository save: pilot ] timeToRun asMilliSeconds. "ms to update"
				[ repository selectOne: VOTestDog where: Dictionary new ] timeToRun asMilliSeconds. "ms to selectOne"
				VOTestPilot allInstances size.
				repository cache compactLimit.
				repository cache reversedObjects size. "size of an internal collection (includes gc'd objects)"
				repository cache reversedObjects slowSize. "size of internal collection (excludes gc'd objects)"
				 } ].

		"(index \\ 700) isZero ifTrue: [ 
			#garbageCollect logCr. 
			Smalltalk garbageCollect ]."
	].

	log inspect.

**Comment by zecke** [comment]
> On 25 Apr 2016, at 20:04, Martín Dias <notifications@github.com> wrote:
> 
> I wanted to learn more of VOMongoCache's behavior and did some tests and benchmarks.
> 
> I found the large number of dead entries (the OID points to nil and viceversa, in other collection). In addition, I watched how the compactLimit changes after performCompact. In most executions it changed from the initial 8000 to 6400. In other executions it went to 2000 or close. What @zecke suggest is to modify minimumCompactLimit (currently 2000), right?
> 
> However, despite I confirm the "dead cache entries", I didn't see latency in basic operations. In the benchmarks, insert, update and selectOne are constant (few milliseconds). Where is the latency?

If you wondered about the name cache. In general the "cache" makes sure that:

```
| a b |

a := repo selectOne: [:each | each uniqueId = 1 ].
b := repo selectOne: [:each | each uniqueId = 1 ].

a == b "will print true because of the OID -> instance cache"
```

I have not analyzed my issue. First it is with Pharo3 where the Dictionary behaves differently than Pharo4/5 and second I see thousands of dead objects. In general my working set is I touch a lot of objects.. and after using it.. will likely be used once more and then be idle for hours again. The data that I use/reference permanently are around ~20 entries.

Anecdotical I see latency decrease if I execute:

```
VOMongoCache allInstancesDo: [:each | each flush]
```

I can not share the actual code or the benchmark and we need a way to reproduce it outside of my application code.

holger

**Comment by zecke** [comment]
This has been addressed in the past.
