### ISSUE TITLE
Rename BaselineOfVoyageMongo to BaselineOfVoyage

### ISSUE THREAD

**Issue by estebanlm** [pharo-nosql/voyage#42]
because I'm resuming to work on the unqlite.org backend, and then we will need to generalise. 

So we can do: 

```Smalltalk
Metacello new 
	githubUser: 'pharo-nosql' project: 'voyage' commitish:'1.?' path: 'mc';
	baseline: 'Voyage';
	load: 'mongo'.
```
etc.

What do you think?

**Comment by noha** [comment]
Sounds good to me

**Comment by tinchodias** [comment]
+1

**Comment by dalehenrich** [comment]
Can hardly wait:) I've got a GemStone backend implementation in the pipeline so the sooner the better :)

**Comment by noha** [comment]
Isn't that done already?

**Comment by tinchodias** [comment]
It really looks like! I close it.
