### ISSUE TITLE
`github://pharo-nosql/mongotalk:1.?/mc` cannot be used in older versions of Pharo without updating Metacello

### ISSUE THREAD

**Issue by dalehenrich** [pharo-nosql/voyage#43]
Since Pharo-4.0 and Pharo-3.0 haven't been built with a relatively recent version of Metacello the tag pattern matching feature is not present and causes build failures [here](https://travis-ci.org/dalehenrich/voyage/jobs/136602520#L264) and [here](https://travis-ci.org/dalehenrich/voyage/jobs/136602521#L264) ... 

Presumably support for Pharo3.0 and Pharo4.0 will be frozen at some point in time anyway, so you might just wire in the tag value for those two platforms (presuming that the version of Metacello installed by default even supports tags ... I think it would) and use the pattern matching for pharo5.0 and beyond

**Comment by estebanlm** [comment]
I see... we will try to keep it working for some time (we have some production users that do not can/want to migrate soon). 
What do you suggest in that case? I suppose to create a moveable tag `1-stable` (or similar) is the best approach?

**Comment by dalehenrich** [comment]
Well let's see. Given that you will want to maintain compatibility with 3.0 and 4.0 for the foreseeable future and given that fact that you are running travis tests before merging, you can pretty much go with the [continuous deployment delivery model](https://en.wikipedia.org/wiki/Continuous_delivery) and just use master in the Baseline. As soon as the MongoTalk guys release features that "cannot be made to work on 3.0 and 4.0" you can use a SHA for 3.0 and 4.0 and continue to use master for 5.0 ...

I agree that pattern matching is nice ... at one point someone (perhaps Johan Brichau) challenged me to come up with a replacement for the symbolic versions used by Seaside (#release3,  #release32, etc.) and the feature was born:)

**Comment by estebanlm** [comment]
ok, I changed baseline as you suggested and now it works fine... I will wait until MongoTalk breaks to go with a SHA :)
