### ISSUE TITLE
move #testSelectManyWithAllKeyword to VOMongoTest

### ISSUE THREAD

**Issue by estebanlm** [pharo-nosql/voyage#44]
because that keyword is mongo-only, as far as I know.
is this correct?

**Comment by tinchodias** [comment]
I think it is not that one but testSelectManyWithLimitAndOffset

**Comment by estebanlm** [comment]
no, is this one, look at it :P 
testSelectManyWithLimitAndOffset is ok, because that functionality can be imitated (and I fact I already do it)

**Comment by noha** [comment]
This is done
