### ISSUE TITLE
Infinite loop when VOMongoConnectionError

### ISSUE THREAD

**Issue by estebanlm** [pharo-nosql/voyage#5]
this is because of this: 

    VOMongoRepositoryResolver>>#execute: aBlock retries: retriesLeft
        aBlock 
		on: NetworkError, BSONError, PrimitiveFailed, ConnectionClosed, VOMongoConnectionError
		do: [ :e | 
			self recoverFromError: e.
			((self isRetryError: e) and: [ retriesLeft > 0 ])
				ifTrue: [ self execute: aBlock retries: retriesLeft - 1 ]
				ifFalse: [ e resignalAs: VOMongoConnectionError new] ].

and a VOMongoConnectionError is thrown in: `VOMongoSessionPool>>#withDatabase:`

... then we have an infinite loop :(

**Comment by noha** [comment]
btw. it is not that a VOMongoConnectionError is needed to initiate the endless loop. Any network error will do as well. The network error will be resignalled as VOMongoConnectionError so every exception will enter the loop

**Comment by tinchodias** [comment]
Any thoughts on how to fix it?

**Comment by estebanlm** [comment]
yes… do not retry the connection infinite times :)
you can retry a configurable amount of times (3 as default) and if that fails raise the error.  

(tbh, I’m not happy with current pool implementation… is very naive… but well…)

Esteban

**Comment by tinchodias** [comment]
Is any of the following 2 solutions ok?

Given the method:

	VOMongoRepositoryResolver>>
	execute: aBlock retries: retriesLeft
		aBlock 
			on: NetworkError, BSONError, PrimitiveFailed, ConnectionClosed, VOMongoConnectionError
			do: [ :e | 
				self recoverFromError: e.
				((self isRetryError: e) and: [ retriesLeft > 0 ])
					ifTrue: [ self execute: aBlock retries: retriesLeft - 1 ]
					ifFalse: [ e resignalAs: VOMongoConnectionError new] ]

1) remove `VOMongoConnectionError` from the "on:"
2) replace `e resignalAs: VOMongoConnectionError new` by `e signal`

Both make the error to show up and break the loop. This was my test:

	VORepositoryTest>>
	testNetworkError
		self
			should: [ VOMongoRepository host: '999.999.999.999' database: 'Voyage-Tests' ]
			raise: Error

**Comment by tinchodias** [comment]
Option 2) seems to lead to many `ConnectionTimedOut: Cannot connect to 127.0.0.1:27017` in terminal when running tests... still learning of Voyage

**Comment by paulwilke** [comment]
I get this error all the time now in a fresh Pharo4 image just by using this code:

`repo := VOMongoRepository`
`	host: '127.0.0.1'`
`	database: 'Heros'.`
`repo enableSingleton.`

`aHero := Hero new.`
`aHero save.`

I use the version provided by pharo4's configuration manager (ThorstenBergmann.40) 

Is there a way around?

**Comment by zecke** [comment]
I am finally bitten by that as well. To state the obvious. ```e resignalAs:``` will not signal an Exception that originates from this block but will re-throw it from where the original exception with signalled.. and re-end up this >>#on:do: handler.. when it is re-thrown and re-thrown.... Specially when just >>withDatabase: [:db | db drop]. no one will be able to catch the VOMongoConnectionError and do something with it. :)

**Comment by noha** [comment]
Any update on this?

**Comment by tinchodias** [comment]
Ah, IMO #47 fixed the loop. Do you have some known case to reproduce?

**Comment by noha** [comment]
No, not yet. Probably I move any of my current projects to newest voyage. Then I will see. If there isn't any counter-reason we could close that issue and reopen if there is negative experience

**Comment by noha** [comment]
Didn't have that problem so far. So I'm closing the issue for now
