### ISSUE TITLE
ciclic references cause duplicated objects when save

### ISSUE THREAD

**Issue by estebanlm** [pharo-nosql/voyage#50]
because of copying hash when solving VOLazyProxy

**Comment by estebanlm** [comment]
this was reported by Sabine, but I saw it too on the catalog updater. I have a fix I will commit now.

**Comment by noha** [comment]
Can you give a reference to the commit containing the fix. To me it is important as I need to decide to upgrade from 1.3.1.2

**Comment by estebanlm** [comment]
here: 86f5268679366bf7a858691a1f64fcbdc37ba4fc
