### ISSUE TITLE
metadata-less repository?

### ISSUE THREAD

**Issue by dalehenrich** [pharo-nosql/voyage#53]
If all of the contributors use either GitFileTree or Iceberg in Pharo and tODE for GemStone we can turn the repo into a metadata-less repository and simplify our lives when we hit the point where we try to use pull requests to merge into the same package ... 

metadata-less repo is basically required if you expect to have multiple active contrinbutors ...

**Comment by tinchodias** [comment]
+1

**Comment by estebanlm** [comment]
+1

**Comment by tinchodias** [comment]
Do metadata-less repos have any bad consequence to consider?

**Comment by estebanlm** [comment]
you loose Monticello history.
people cannot contribute "just like that" (but they are not doing it right now)

**Comment by dalehenrich** [comment]
Yes, the tools have to be in place for everyone to be able to contribute via pull request and if the tools aren't quite in place then it is premature to convert ...

**Comment by noha** [comment]
So did we all agree that we are all using the right tools to do the switch?

**Comment by noha** [comment]
bump! anyone?
