### ISSUE TITLE
MNU VOMongoToManyDescription>>jsonName

### ISSUE THREAD

**Issue by SabineMa** [pharo-nosql/voyage#56]
when selecting some data with voyage version 1.4.1  from mongo, I geht MNU VOMongoToManyDescription>>jsonName. I assume this was earlier mongoName and is not yet implemented.  mongoName instead of jsonName works

**Comment by estebanlm** [comment]
yes, `#mongoName` is deprecated and should be `#jsonName` now, but then... `VOMongoToManyDescription` is also deprecated and you should use `VOToManyDescription`.

Maybe you need to migrate your `VOMongo*` descriptions?

I was just thinking about this... yesterday I was sure it was a bug but today I remarked the use of an older class... yet, I think I should provide some "legacy" package to provide backward compatibility... what do you think?

**Comment by SabineMa** [comment]
I did not know that the classes were replaced.
I just changed
*VOMongoToManyDescription with VOToManyDescription
*VOMongoToOneDescription with VOToOneDescription. 
*VOMongoContainer with VOContainer
* VOMongoMissing with VOMissingObject
*VOMongoTransientDescription with VOTransientDescription 

and it seems to work.

Questions: 
1) Do you have some documentation or can you tell me, what else to change?  Would it have been possible that I see that before finding it in the code when creating a new image? Like this, It was a surprise this morning and I had other plans for my work today :-)

2) I assume http://smallworks.eu/web/blog?_k=QmHE8wBxIrgUtEmA has old code, too?
also the book:-))

3) this is attached to 1) It would be great to have a stable version and so have the possibility to decide when to fight with the changes. Is that possible? Currently I load only the Baseline with:
 spec
	className: 'BaselineOfVoyage';
	repository: 'github://pharo-nosql/voyage/mc';
	loads: #('mongo')

How can I load a stable version with the duplicates  bug fixed?

So, to answer your question - my fox is running and I don't need legacy package.

**Comment by noha** [comment]
I think this is done. I opened #67 to not forget to update documentation
