### ISSUE TITLE
unqlite.dll library requires libgcc_s_dw2-1-dll

### ISSUE THREAD

**Issue by estebanlm** [pharo-nosql/voyage#59]
a problem in compilation (we need to compile it with static bindings

**Comment by estebanlm** [comment]
ok, this was more an error of PunQLite, but I think I fixed it... now I need someone to test... @astares ;)

**Comment by estebanlm** [comment]
finally, I got what I believe is a working version @astares :)
I updated it at https://github.com/pharo-nosql/PunQLite/releases/download/stable/unqlite.dll

So a fresh (development) version should *now* work as expected. Can you give it a try?

**Comment by estebanlm** [comment]
yeah, this is fixed (I forget to close the issue)

**Comment by astares** [comment]
confirm that it is working
