### ISSUE TITLE
Test more packages with travis?

### ISSUE THREAD

**Issue by tinchodias** [pharo-nosql/voyage#66]
Current .smalltalk.ston is:

```
SmalltalkCISpec {
  #loading : [
    SCIMetacelloLoadSpec {
      #baseline : 'Voyage',
      #directory : 'mc',
          #load : [ 'mongo tests' ],      
      #platforms : [ #pharo ]
    }
  ]
}
```

i.e. it doesn't include either memory nor unqlite. 
(Also, #62 introduces Voyage-Mongo-MultipleImageTests package, which I would like to add...)

**Comment by noha** [comment]
unqlite has its own build. Should we include the memory tests in this build? I'm for it

**Comment by tinchodias** [comment]
I agree for memory
