### ISSUE TITLE
VOLazyProxy, "keeping hash" and "copyHash:false"

### ISSUE THREAD

**Issue by tinchodias** [pharo-nosql/voyage#69]
Hi,

The class VOLazyProxy has this method:
```
becomeForwardKeepingHash: otherObject
	"Primitive. All variables in the entire system that used to point to the receiver now point to the argument.
	If copyHash is true, the argument's identity hash bits will be set to those of the receiver.
	Fails if either argument is a SmallInteger."

	(Array with: self)
		elementsForwardIdentityTo: (Array with: otherObject)
		copyHash: false
```

Become is a delicate feature whose details sometimes I don't grasp... so I wonder if this method isn't buggy, since "keeping hash" in the selectors sounds like "copyHash" parameter should be true.

Thanks.

**Comment by estebanlm** [comment]
no, it is like that, believe me :)
copying hash will actually set the hash of the proxy to the real object, breaking the cache.

**Comment by tinchodias** [comment]
good, thanks!

On Tue, Oct 11, 2016 at 3:29 PM, Esteban Lorenzano <notifications@github.com

**Comment by noha** [comment]
Yes, copyHash true......collection.....very bad!!!
