### ISSUE TITLE
Fix VOMongoRepository>>rawSelectMany:where:

### ISSUE THREAD

**Issue by tinchodias** [pharo-nosql/voyage#78]
Unused (only 1 sender and 1 implementor... itself)

```
rawSelectMany: aClass where: aDictionary
    ^resolver rawSelectMany: aClass where: aDictionary
```

**Comment by estebanlm** [comment]
I don't know... it is useful when you do not want to take the effort to convert a query result into objects (for listings, etc.).
I remember I implemented it because I needed it someplace (but I do not remember where ;) )

**Comment by tinchodias** [comment]
ok, I see, but then we need to implement the method in the resolver (in my image there was no implementor there)

**Comment by noha** [comment]
this is obsolete
