### ISSUE TITLE
Tests randomly fail when they are not run in isolation

### ISSUE THREAD

**Issue by tinchodias** [pharo-nosql/voyage#8]
Tests run ok individually, but they fail when reusing the instance of VOMongoTestResource (a SUnit resource). The #tearDown of such resource executes `VOMongoTestResource reset` and the #tearDown of the test case just uses `VOMongoRepository>>removeAll:` to (fast?) reset the resources. Not sure if that's correct, but in any case it shows that: #removeAll: is not removing all elements, which is buggy.

The following code reproduces the bug. It halts around iteration 19 in my computer.

	"From resource's tearDown"
	VOMongoTestResource reset.

	1 to: 30 do: [ :index |

		"From #testSave test case"

		| pilot pilots repository |
		repository := VOMongoTestResource current repository.
	
		pilot := VOTestPilot new
			name: 'Esteban';
			pet: (VOTestDog new name: 'Doggie').
		repository save: pilot.
	
		pilots := repository selectAll: VOTestPilot.

		1haltIf: [ pilots size > 1 ].

		"From test case's tearDown"

		repository 
			removeAll: VOTestPet;
			removeAll: VOTestPilot.
	].

	"From resource's tearDown"
	VOMongoTestResource reset.

**Comment by Ironirc** [comment]
Confirming that random tests fail intermittently

**Comment by tinchodias** [comment]
Thanks, and I guess your issue #9 is related.

**Comment by tinchodias** [comment]
Hi, an update.  Some observations:

1. The bug happens also in a simplified script which only save: and removeAll: a VOTestPilot, without need of the VOTestPet.
2. It also happens when using `repository remove:` instead of `repository removeAll:`.
3. I've been understanding more of how Voyage and Mongo work, and also logging in Transcript the low-level operations of the script above reported: the insert and delete mongo operations are written in the right order in the socket streams. 
4. This bug doesn't happen with a `25 milliSeconds asDelay wait.` just after the removing operation. But 5 milliseconds are not enough.

(Without completely understanding Mongo+Voyage yet) I suppose that the source of the problem is concurrency in the mongo server, and I suspect this problem appeared after the recent "futures" optimization because now it's too fast :)

Does it make sense? What do you think?

**Comment by tinchodias** [comment]
Fixed with #61
