### ISSUE TITLE
Force sync in VOMongoTest>>waitForWriteOperation

### ISSUE THREAD

**Issue by tinchodias** [pharo-nosql/voyage#81]
In [a PR's discussion](https://github.com/pharo-nosql/voyage/pull/61), @zecke said:
> Again you can use >>#command: with getLastError and force a sync? Then the last write/delete/op must have succeeded.

referred to mc/Voyage-Mongo-Tests.package/VOMongoTest.class/instance/waitForWriteOperation.st

**Comment by noha** [comment]
Can be closed?

**Comment by tinchodias** [comment]
It's not very important but it should improve test running time... let me try if it works. 
It should, according to [current doc](https://docs.mongodb.com/manual/reference/command/getLastError/#dbcmd.getLastError):
> In previous versions, clients typically used the getLastError in combination with a write operation to verify that the write succeeded.

**Comment by tinchodias** [comment]
We can close it... I didn't arrive to a PR. For the record: 

I rewrote the test method as:
~~~
VOMongoTest>>
waitForWriteOperation
	repository ensureFinishedLastWriteOperation
~~~

That ended into:
~~~
VOMongoRepositoryResolver >>
ensureFinishedLastWriteOperation
	self execute: [ self writingPool withDatabase: [ :db | db lastError ] ]
~~~

Where `#lastError` executes the mongo command `{ getLastError: 1 }`.
I then I realized it's wrong, since the definition of [getLastError](https://docs.mongodb.com/manual/reference/command/getLastError/#dbcmd.getLastError) says:
> Returns the error status of the preceding write operation on the current connection.

This means that after a `VOMongoRepository` write operation the db returns to the pool and afterwards we could be asking the last error to a wrong db (connection).

So, unless you have a better solution, we close this issue and keep the 50 ms delay in the tests.
