### ISSUE TITLE
Documentation: In the EnterprisePharo chapter there is a reference to VOMongoToOneDescription

### ISSUE THREAD

**Issue by jecisc** [pharo-nosql/voyage#82]
If I am not wrong it is now called VOToOneDescription. Is that right?

**Comment by jecisc** [comment]
If it is right I will move the issue to Enterprise Pharo book

**Comment by jecisc** [comment]
Also maybe it could be cool to add the fact we need to reset the cache to the doc.

**Comment by SabineMa** [comment]
https://github.com/pharo-nosql/voyage/issues/56

CyrilFerlicot <notifications@github.com> schrieb am Di. 10. Jan. 2017 um
15:41:

**Comment by noha** [comment]
What is the status here?

**Comment by noha** [comment]
Relates to #105
