### ISSUE TITLE
docs links in the readme do not work

### ISSUE THREAD

**Issue by peteruhnak** [pharo-nosql/voyage#86]
No link in the docs section works https://github.com/pharo-nosql/voyage#documentation

ci points to "Error: no workspace"
and links to smallworks.eu to "502 Bad Gateway nginx/1.4.1 (Ubuntu)"

**Comment by estebanlm** [comment]
the smallworks site (my site) was down... I need to migrate that site :)
anyway the links to there are working now.

**Comment by peteruhnak** [comment]
thanks!

**Comment by estebanlm** [comment]
but the link to the book needs to be restored.

**Comment by tinchodias** [comment]
I just checked that the urls work in https://github.com/pharo-nosql/voyage#documentation
