### ISSUE TITLE
Test for Voyage failure to materialize in some situation

### ISSUE THREAD

**Issue by hilaire** [pharo-nosql/voyage#87]
Here is a test case to expose the materialization problem I discussed
previously[1].

Hopefully the test will help to track the problem.

Note: With memory repository it is of course fine, so MongoDB resource
is needed for the test.

[1] http://forum.world.st/Voyage-and-instances-retrieving-tt4936868.html

[Voyage-Mongo-Test-Materialization.st.zip](https://github.com/pharo-nosql/voyage/files/838430/Voyage-Mongo-Test-Materialization.st.zip)

**Comment by SabineMa** [comment]
In the Enterprise Book it is written "Note that this way of querying only works for querying values of the object but not values of references to other objects. For such case you should build your query using ids, as traditionally done in relational database, which we talk about next. However the best solution in the Mongo spirit of things is to revisit the object model to avoid relationships that are expressed with foreign keys."

**Comment by hilaire** [comment]
I guess it is the explanation then.
How will you revisit the object model? With an iterator and sending #value to each foreign object?

**Comment by SabineMa** [comment]
First I would re-think my model (the model how the data is stored in mongo).
It does as I understand not always make sense to have the same model as you
would have in a relational database.

Example I have one person has N trips which has N receipts.
In a relational database I would have a table With trips, one with receipts
and one with persons.
in Smalltalk I have instances of person, trip and receipt.

But in Mongo I ended up with one document per trip having the receipts
"inline"

This is only my experience, possibly your situation is another one.
But rethinking about your document model perhaps solves your problem.

hilaire <notifications@github.com> schrieb am Do. 16. März 2017 um 14:45:

**Comment by noha** [comment]
Following the mail thread this is something voyage isn‘t supporting a probably never will. Closing now
