### ISSUE TITLE
VOSeedVersionGenerator>>#newVersion is broken in Pharo6

### ISSUE THREAD

**Issue by zecke** [pharo-nosql/voyage#90]
```
newVersion
	^UUIDGenerator new makeSeed
```

no one implements makeSeed. @estebanlm are you okay to remove that class?

**Comment by estebanlm** [comment]
it is there just for backward compatibility reasons... yes, I'd be ok with removing it :)

**Comment by zecke** [comment]
Ah I see. Does Voyage master still load on Pharo4 and do you want to support it?

**Comment by noha** [comment]
This should be fixed, no?

**Comment by estebanlm** [comment]
yes, I think
