### ISSUE TITLE
compact limit always will be higher and higher

### ISSUE THREAD

**Issue by jmari** [pharo-nosql/voyage#94]
In VOCache 
private
recalculateCompactLimit 
...
...	
	(occupiedPercent >= 85) 
		ifTrue: [ 
			newSize := self compactLimit  + (self compactLimit * 20 / 100) truncated.
			self compactLimit: (newSize max: self class maximumCompactLimit) ].
...
must be 
                        self compactLimit: (**newSize min:** self class maximumCompactLimit) ].

**Comment by zecke** [comment]
I don't know the code but from the logic that newSize can be bigger maximumCompactLimit sounds wrong. :)
