### ISSUE TITLE
VOLazyProxy>>#doesNotUnderstand: not fit for concurrency

### ISSUE THREAD

**Issue by zecke** [pharo-nosql/voyage#95]
In Pharo6 I have two Processed that seem to work on the same object and when accessing a relation (represented through an instance of a VOLazyProxy subclass) I get a DNU with MyClass(Object)>>#doesNotUnderstand: #becomeForwardKeepingHash:

It seems that execution can change between...

```
	realObject := self obtainRealObject.
...
	self becomeForwardKeepingHash: realObject.
```

and then becomeForwardKeepingHash: is not sent to the VOLazyProxy but to the real object already!

**Comment by zecke** [comment]
@estebanlm @noha The issue seems quite obvious once one runs into it. I tried to hack around by changing defaultLazyProxy to false (to simulate beEager) but that failed on a stress test (I don't have the log around..) as well..

**Comment by zecke** [comment]
I solve it by installing a becomeForwardKeepingHash: extension to object... with a no-op... for concurrency the question is if obtainRealObject returns the same (address) object as well?

**Comment by SabineMa** [comment]
@estebanlm @noha
I ran into the same issue when trying to use 2 images and work on the same object. 
It seems that it can be fixed with Holgers code above

```
MyClass>>obtainRealObject and
MyClass>>becomeForwardKeepingHash:
both doing nothing 
```

@zecke what is your experience, does it work like this?

can we go into production with this? We want to go online asap and this is important for us

**Comment by zecke** [comment]
@SabineMa I am running with the Object>>#becomeForwardKeepingHash: in production since 2018.

**Comment by noha** [comment]
This is a duplicated of #75

**Comment by noha** [comment]
using Object>>becomeForwardKeepingHash: is now the default.
