### ISSUE TITLE
Fix some tests that output "External Image Failed: 256"

### ISSUE THREAD

**Issue by tinchodias** [pharo-nosql/voyage#98]
They are tests created by me, that use ImageWorker to spawn a new os process with a parallel pharo image to force some concurrency situations.

To reproduce, see travis, or locally load as in readme but with 'mongo tests multiple'

**Comment by tinchodias** [comment]
It should work at least:

```
ImageWorker 
		do: [ 1+2 ]
		within: 1 seconds 
		onTimeout: [ self error: 'timeout' ].
```

but no... now I wonder what's 256 error code.

**Comment by noha** [comment]
This should be fixed now
